# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


use_frameworks!
target ‘QueueApp’ do   
    pod 'RestKit', '~> 0.25.0'
    pod 'FXKeychain', '~> 1.5'
    pod 'ActionSheetPicker-3.0', '~> 2.0'
    pod 'SWRevealViewController', '~> 2.3'    
end

